imports:
  - { resource: ./application.yaml }

services:
  CourtsManager.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@CourtsManager.Shared.ConnectionManager']
